#!/usr/bin/env bash

## Description: Run jira-prepare-commit-msg commands on host.
## Usage: jira-prepare-commit-msg [jira-prepare-commit-msg command]
## Example: "ddev jira-prepare-commit-msg.config"

source $(dirname $0)/../../../scripts/utils.sh

# Get the commit path
commit_path=$(get_commit_path)

echo "commit_path: $commit_path"
# Run the jira-prepare-commit-msg command with the commit path
ddev exec cd $commit_path && npx jira-prepare-commit-msg $1
