#!/usr/bin/env bash

## Description: Run lint-staged commands on host.
## Usage: lint-staged [lint-staged command]
## Example: "ddev lint-staged"

source $(dirname $0)/../../../scripts/utils.sh

# Get the commit path
commit_path=$(get_commit_path)

echo "commit_path: $commit_path"
# Run the lint-staged command with the commit path
ddev exec npx lint-staged --no-stash --cwd "$commit_path"

