#!/usr/bin/env bash

## Description: Run phpcbf commands in the web container.
## Usage: phpcbf [phpcbf command]
## Example: "ddev phpcbf"

phpcbf --standard=Drupal,DrupalPractice --extensions=php,module,inc,install,test,profile,theme --ignore=node_modules "$@"

exit=$?

# Exit code 0 is important for the pre-commit hook to work.
# See https://github.com/squizlabs/PHP_CodeSniffer/issues/1818
if [[ $exit -eq 0 || $exit -eq 1 ]]; then
    exit 0
fi

exit $exit
