#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Don't run this hook on CI.
[ -n "$CI" ] && exit 0

# Validate branch name before commit.
ddev npx validate-branch-name

source $(dirname $0)/../scripts/utils.sh

# Get the commit path
commit_path=$(get_commit_path)

# Run the lint-staged command with the commit path
ddev npx lint-staged --no-stash -d --cwd "$commit_path"

