#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Don't run this hook on CI.
[ -n "$CI" ] && exit 0

# Validate branch name before commit.
ddev npx validate-branch-name

# Run the lint-staged command.
ddev npx lint-staged --no-stash

